[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[etherscan]
avalanche = { key = "${ETHERSCAN_API_KEY}" }

[rpc_endpoints]
avalanche = "${AVALANCHE_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
